{{- if or (and .Values.jwtSecret (not .Values.auth.existingSecret)) (and .Values.database.dsn (not .Values.database.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- if and .Values.jwtSecret (not .Values.auth.existingSecret) }}
  jwt-secret: {{ .Values.jwtSecret | quote }}
  {{- end }}
  {{- if and .Values.database.dsn (not .Values.database.existingSecret) }}
  db-dsn: {{ .Values.database.dsn | quote }}
  {{- end }}
{{- end }}
